// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmB1b_V4ou7lCDAsDibF7vNwLBmnYoGg8',
    appId: '1:83100273629:web:fb4bb728fe1e89edae4434',
    messagingSenderId: '83100273629',
    projectId: 'chatapp-69a31',
    authDomain: 'chatapp-69a31.firebaseapp.com',
    storageBucket: 'chatapp-69a31.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVU1MCGIxLWGIWg1wcPg5RGDzvA3Af-tQ',
    appId: '1:83100273629:android:0b0237d05bc96abfae4434',
    messagingSenderId: '83100273629',
    projectId: 'chatapp-69a31',
    storageBucket: 'chatapp-69a31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnlE3CKYZHis1bipOErg6cvhqoK_XiLxI',
    appId: '1:83100273629:ios:691513a7cb70c56dae4434',
    messagingSenderId: '83100273629',
    projectId: 'chatapp-69a31',
    storageBucket: 'chatapp-69a31.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnlE3CKYZHis1bipOErg6cvhqoK_XiLxI',
    appId: '1:83100273629:ios:691513a7cb70c56dae4434',
    messagingSenderId: '83100273629',
    projectId: 'chatapp-69a31',
    storageBucket: 'chatapp-69a31.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );
}
